# Generated by Django 4.2 on 2023-05-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_alter_item_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('finalizada', 'Finalizada')], default='ativa', max_length=20),
        ),
    ]
