# Generated by Django 4.2 on 2023-06-25 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_cliente_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='venda.endereco'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=150, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=150, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(max_length=150, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='numero'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='país',
            field=models.CharField(default='Brasil', max_length=150, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='rua',
            field=models.CharField(max_length=150, verbose_name='rua'),
        ),
    ]
