# Generated by Django 4.2 on 2023-06-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0004_alter_cliente_endereco_alter_endereco_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cep',
            field=models.CharField(default=None, max_length=8, verbose_name='cep'),
        ),
    ]
