# Generated by Django 4.2 on 2023-06-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0006_alter_endereco_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='cep',
        ),
    ]
