# Generated by Django 4.2 on 2023-06-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0007_remove_endereco_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cep',
            field=models.CharField(default='12345678', max_length=8),
        ),
    ]
