# Generated by Django 4.2 on 2023-06-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0008_endereco_cep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='país',
            new_name='pais',
        ),
    ]
