version: '3.9'

services:
  mariadb:
    container_name: controlcash-database
    image: mariadb:latest
    volumes:
      - $HOME/docker/mariadb:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=$DB_NAME
      - MARIADB_USER=$DB_USER
      - MARIADB_PASSWORD=$DB_PASSWORD
      - MARIADB_ROOT_PASSWORD=$DB_PASSWORD
    restart: always
    ports:
      - 3306:3306
    networks:
      - controlcash-net

  web:
    container_name: controlcash-app
    image: controlcash:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c  "sleep 10
              python manage.py collectstatic --noinput
              python manage.py migrate --noinput
              gunicorn controlCash.wsgi:application --bind 0.0.0.0:8000"

    volumes:
      - .:/code
    depends_on:
      - mariadb
    expose:
      - 8000
    networks:
      - controlcash-net
  
  nginx:
    container_name: controlcash-nginx
    build: ./nginx 
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - controlcash-net
    volumes:
      - .:/code
networks:
  controlcash-net:
    driver: bridge