# Generated by Django 4.2 on 2023-07-16 14:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('periodica', models.BooleanField(default=False, verbose_name='periódica')),
                ('vencimento', models.DateField(verbose_name='data de vencimento')),
                ('paga', models.BooleanField(default=False)),
            ],
        ),
    ]
