# Generated by Django 4.2 on 2023-05-25 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Preço Venda')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('quantidade_estoque', models.PositiveIntegerField(verbose_name='Quatidade')),
                ('data_registro', models.DateField(auto_now_add=True, verbose_name='Data')),
            ],
        ),
    ]
