# Generated by Django 4.2 on 2023-05-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=True)),
                ('nome', models.CharField(max_length=150)),
                ('precoVenda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('quantidadeEstoque', models.IntegerField()),
                ('dataRegistro', models.DateField()),
            ],
        ),
    ]
