# Generated by Django 4.2 on 2023-05-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='dataRegistro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='precoVenda',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Venda'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidadeEstoque',
            field=models.PositiveIntegerField(),
        ),
    ]
