# Generated by Django 4.2 on 2023-05-16 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_dataregistro_alter_produto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='precoVenda',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Preço Venda'),
        ),
    ]
