# Generated by Django 4.2 on 2023-05-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_dataregistro_alter_produto_descricao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='dataRegistro',
            new_name='data_registro',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='precoVenda',
            new_name='preco_venda',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='quantidadeEstoque',
            new_name='quantidade_estoque',
        ),
    ]
