# Generated by Django 4.2 on 2023-05-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('R', 'Recebido'), ('C', 'Cancelado')], default='P', max_length=1)),
                ('id_cliente', models.IntegerField()),
            ],
        ),
    ]
