# Generated by Django 4.2 on 2023-05-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('taxas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
