# Generated by Django 4.2 on 2023-06-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0002_formapagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido'), ('cacelado', 'Cancelado')], default='pendente', max_length=8),
        ),
    ]
