# Generated by Django 4.2.2 on 2023-07-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0003_alter_pagamento_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormaPagamento',
        ),
    ]
